# JDK, JRE, and JVM

## Overview

JDK, JRE, and JVM are the core components of the Java platform. Understanding their roles is essential to know how Java programs are developed and executed.

---

# What is JDK?

**JDK (Java Development Kit)** is a software development kit used to develop Java applications.

It provides all the tools required to write, compile, debug, and run Java programs.

## JDK Contains

- Compiler (`javac`)
- Java Launcher (`java`)
- JVM (Java Virtual Machine)
- Runtime Libraries
- Debugging Tools
- Development Utilities

---

# Responsibilities of JDK

- Develop Java applications.
- Compile Java source code.
- Provide tools for debugging.
- Provide the runtime environment required to execute Java programs.

---

# What is JRE?

**JRE (Java Runtime Environment)** provides everything required to run a Java program.

It is responsible for providing the runtime environment needed during program execution.

## JRE Contains

- JVM (Java Virtual Machine)
- Java Runtime Libraries
- Supporting Runtime Files

---

# Responsibilities of JRE

- Provides the runtime environment.
- Provides the JVM.
- Provides Java runtime libraries.
- Enables Java programs to execute.

> **Note:** JRE does **not** compile Java programs. Compilation is performed by the JDK's compiler (`javac`).

---

# What is JVM?

**JVM (Java Virtual Machine)** is the engine that executes Java programs.

It reads Java Bytecode and converts it into Machine Code that the CPU can understand.

---

# Responsibilities of JVM

- Loads Bytecode.
- Verifies Bytecode.
- Uses the runtime libraries provided by the JRE.
- Converts Bytecode into Machine Code.
- Executes the program.

---

# Relationship Between JDK, JRE, and JVM

```text
JDK
│
├── Compiler (javac)
├── Java Launcher (java)
├── JRE
│     │
│     ├── JVM
│     └── Runtime Libraries
│
└── Development Tools
```

---

# Difference Between JDK, JRE, and JVM

| Component | Purpose | Contains |
|-----------|---------|----------|
| JDK | Develop Java applications | Compiler, JRE, JVM, Development Tools |
| JRE | Run Java applications | JVM and Runtime Libraries |
| JVM | Execute Java programs | Executes Bytecode |

---

# Java Compilation and Execution

```text
Main.java
      │
      ▼
Compiler (javac)
      │
      ▼
Main.class
(Bytecode)
      │
      ▼
JRE
      │
      ├── Provides Runtime Libraries
      └── Provides JVM
                │
                ▼
JVM
      │
      ▼
Machine Code
      │
      ▼
CPU
      │
      ▼
Output
```

---

# Roles of Each Component

## JDK

- Provides development tools.
- Compiles Java source code.
- Includes the JRE.

---

## JRE

- Provides the runtime environment.
- Provides runtime libraries.
- Provides the JVM.

---

## JVM

- Uses the runtime libraries provided by the JRE.
- Converts Bytecode into Machine Code.
- Executes Java programs.

---

# Important Terms

## Source Code

Code written by the programmer.

Example:

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello");
    }
}
```

File:

```text
Main.java
```

---

## Compiler (`javac`)

Converts Java source code into Bytecode.

```text
Main.java
      │
      ▼
javac
      │
      ▼
Main.class
```

---

## Bytecode

Bytecode is the intermediate code generated by the Java compiler.

- Stored inside `.class` files.
- Platform Independent.
- Executed by the JVM.

Example:

```text
getstatic
ldc
invokevirtual
return
```

---

## Machine Code

Machine Code is the binary language understood by the CPU.

Example:

```text
1010101010011010
```

---

# Summary

| Component | Main Responsibility |
|-----------|---------------------|
| JDK | Provides development tools for Java. |
| Compiler (`javac`) | Compiles `.java` into `.class`. |
| JRE | Provides the runtime environment, JVM, and runtime libraries. |
| JVM | Uses the runtime libraries, converts Bytecode into Machine Code, and executes the program. |
| CPU | Executes Machine Code. |

---

# Key Points

- JDK is used for Java development.
- JDK provides the compiler (`javac`).
- JRE provides the runtime environment.
- JRE provides the JVM and runtime libraries.
- JVM executes Bytecode.
- Bytecode is platform-independent.
- Machine Code is platform-dependent.
- The CPU executes Machine Code.
